# Generated by Django 6.1.1 on 2026-10-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='source_url',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
